[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "6GrvCvjDiSopTEsurpV3CF8tWR8TwuonCHM2H5pYvzEp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thiagorochatr/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"